version: "3.4"
services:
    traefik:
        image: traefik:v2.2
        container_name: traefik
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.toml:/traefik.toml
            - ./traefik_dynamic.toml:/traefik_dynamic.toml
            - ./acme.json:/acme.json
        ports:
            - "80:80"
            - "443:443"
        networks:
            - web    

    nop:
        image: nopcommerceteam/nopcommerce:latest
        container_name: nop
        restart: always
        volumes:
            - appdata:/app
        networks:
            - internal
            - web    
        ports:
            - "5000:80"               
        labels:
            - traefik.http.routers.nop.rule=Host(`www.yourwebsite.com`, `yourwebsite.com`)
            - traefik.http.routers.nop.tls=true
            - traefik.http.routers.nop.tls.certresolver=lets-encrypt
            - traefik.port=80
        depends_on:
            - db      
                 
    db:
        image: "mysql:latest"
        container_name: db
        command: "--default-authentication-plugin=mysql_native_password"
        restart: always
        ports:
          - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "verysecurepassword"
            MYSQL_DATABASE: nopdb
        volumes:
            - dbdata:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.conf
        networks:
             - internal
        labels:
             - traefik.enable=false
    adminer:
        image: adminer:4.6.3-standalone
        container_name: adminer
        restart: always
        labels:
            - traefik.http.routers.adminer.rule=Host(`db-admin.yourwebsite.com`)
            - traefik.http.routers.adminer.tls=true
            - traefik.http.routers.adminer.tls.certresolver=lets-encrypt
            - traefik.port=8080
        networks:
            - internal
            - web
        depends_on:
            - db                         

networks:
  web:
    external: true
  internal:
    external: false

volumes:
    appdata:
    dbdata:
        

          

    